/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import type { Context } from './../context'
import type { core } from 'nexus'
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    DateTime<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    DateTime<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void // "DateTime";
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BlogByIdInput: {
    // input type
    id: string // String!
  }
  BlogCommentByIdInput: {
    // input type
    id: string // String!
  }
  BlogCommentsByParentCommentIdInput: {
    // input type
    id: string // String!
  }
  BlogCommentsByPostIdInput: {
    // input type
    id: string // String!
  }
  BlogCommentsByUserIdInput: {
    // input type
    id: string // String!
  }
  BlogPostByIdInput: {
    // input type
    id: string // String!
  }
  BlogPostsByBlogIdInput: {
    // input type
    id: string // String!
  }
  BlogPostsByUserIdInput: {
    // input type
    id: string // String!
  }
  BlogsByUserIdInput: {
    // input type
    id: string // String!
  }
  CreateBlogCommentInput: {
    // input type
    authorId: string // String!
    blogPostId: string // String!
    content: string // String!
    parentId?: string | null // String
  }
  CreateBlogInput: {
    // input type
    authorId: string // String!
    description: string // String!
    name: string // String!
  }
  CreateBlogPostInput: {
    // input type
    authorId: string // String!
    blogId: string // String!
    content: string // String!
    published: boolean // Boolean!
    title: string // String!
  }
  UpdateBlogCommentInput: {
    // input type
    content: string // String!
    id: string // String!
  }
  UpdateBlogInput: {
    // input type
    description: string // String!
    id: string // String!
  }
  UpdateBlogPostInput: {
    // input type
    content: string // String!
    id: string // String!
    published: boolean // Boolean!
    title: string // String!
  }
  UpdateUserInput: {
    // input type
    bio: string // String!
    id: string // String!
  }
  UserByEmailInput: {
    // input type
    email?: string | null // String
  }
  UserByIdInput: {
    // input type
    id: string // String!
  }
  UserByUsernameInput: {
    // input type
    username?: string | null // String
  }
}

export interface NexusGenEnums {}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Account: {
    // root type
    access_token?: string | null // String
    expires_at?: number | null // Int
    id: string // String!
    id_token?: string | null // String
    provider: string // String!
    providerAccountId: string // String!
    refresh_token?: string | null // String
    scope?: string | null // String
    session_state?: string | null // String
    token_type?: string | null // String
    type: string // String!
    userId: string // String!
  }
  Blog: {
    // root type
    authorId: string // String!
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    description?: string | null // String
    id: string // String!
    name?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  BlogComment: {
    // root type
    authorId: string // String!
    blogPostId: string // String!
    content: string // String!
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    id: string // String!
    parentId?: string | null // String
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  BlogPost: {
    // root type
    authorId: string // String!
    blogId: string // String!
    content: string // String!
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    id: string // String!
    published: boolean // Boolean!
    title: string // String!
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
  }
  Mutation: {}
  Query: {}
  Session: {
    // root type
    expires?: NexusGenScalars['DateTime'] | null // DateTime
    id: string // String!
    sessionToken: string // String!
    user?: NexusGenRootTypes['User'] | null // User
    userId: string // String!
  }
  User: {
    // root type
    accounts?: Array<NexusGenRootTypes['Account'] | null> | null // [Account]
    bio?: string | null // String
    createdAt?: NexusGenScalars['DateTime'] | null // DateTime
    email?: string | null // String
    emailVerified?: NexusGenScalars['DateTime'] | null // DateTime
    id: string // String!
    image?: string | null // String
    name?: string | null // String
    sessions?: Array<NexusGenRootTypes['Session'] | null> | null // [Session]
    updatedAt?: NexusGenScalars['DateTime'] | null // DateTime
    username?: string | null // String
  }
  VerificationToken: {
    // root type
    expires: string // String!
    identifier: string // String!
    token: string // String!
  }
}

export interface NexusGenInterfaces {}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Account: {
    // field return type
    access_token: string | null // String
    expires_at: number | null // Int
    id: string // String!
    id_token: string | null // String
    provider: string // String!
    providerAccountId: string // String!
    refresh_token: string | null // String
    scope: string | null // String
    session_state: string | null // String
    token_type: string | null // String
    type: string // String!
    user: NexusGenRootTypes['User'] | null // User
    userId: string // String!
  }
  Blog: {
    // field return type
    author: NexusGenRootTypes['User'] | null // User
    authorId: string // String!
    blogPosts: Array<NexusGenRootTypes['BlogPost'] | null> // [BlogPost]!
    createdAt: NexusGenScalars['DateTime'] | null // DateTime
    description: string | null // String
    id: string // String!
    name: string | null // String
    updatedAt: NexusGenScalars['DateTime'] | null // DateTime
  }
  BlogComment: {
    // field return type
    author: NexusGenRootTypes['User'] | null // User
    authorId: string // String!
    blogComments: Array<NexusGenRootTypes['BlogComment'] | null> | null // [BlogComment]
    blogPost: NexusGenRootTypes['BlogPost'] | null // BlogPost
    blogPostId: string // String!
    content: string // String!
    createdAt: NexusGenScalars['DateTime'] | null // DateTime
    id: string // String!
    parent: NexusGenRootTypes['BlogComment'] | null // BlogComment
    parentId: string | null // String
    updatedAt: NexusGenScalars['DateTime'] | null // DateTime
  }
  BlogPost: {
    // field return type
    author: NexusGenRootTypes['User'] | null // User
    authorId: string // String!
    blog: NexusGenRootTypes['Blog'] | null // Blog
    blogComments: Array<NexusGenRootTypes['BlogComment'] | null> | null // [BlogComment]
    blogId: string // String!
    content: string // String!
    createdAt: NexusGenScalars['DateTime'] | null // DateTime
    id: string // String!
    published: boolean // Boolean!
    title: string // String!
    updatedAt: NexusGenScalars['DateTime'] | null // DateTime
  }
  Mutation: {
    // field return type
    UpdateBlogCommentInput: NexusGenRootTypes['BlogComment'] | null // BlogComment
    createBlog: NexusGenRootTypes['Blog'] | null // Blog
    createBlogComment: NexusGenRootTypes['BlogComment'] | null // BlogComment
    createBlogPost: NexusGenRootTypes['Blog'] | null // Blog
    updateBlog: NexusGenRootTypes['Blog'] | null // Blog
    updateBlogPost: NexusGenRootTypes['Blog'] | null // Blog
    updateUser: NexusGenRootTypes['User'] | null // User
  }
  Query: {
    // field return type
    allBlogComments: Array<NexusGenRootTypes['BlogComment'] | null> | null // [BlogComment]
    allBlogPosts: Array<NexusGenRootTypes['BlogPost'] | null> | null // [BlogPost]
    allBlogs: Array<NexusGenRootTypes['Blog'] | null> | null // [Blog]
    allUsers: Array<NexusGenRootTypes['User'] | null> | null // [User]
    blogById: NexusGenRootTypes['Blog'] | null // Blog
    blogCommentById: NexusGenRootTypes['BlogComment'] | null // BlogComment
    blogCommentsByParentCommentId: Array<NexusGenRootTypes['BlogComment'] | null> // [BlogComment]!
    blogCommentsByPostId: Array<NexusGenRootTypes['BlogComment'] | null> // [BlogComment]!
    blogCommentsByUserId: Array<NexusGenRootTypes['BlogComment'] | null> // [BlogComment]!
    blogPostById: NexusGenRootTypes['BlogPost'] | null // BlogPost
    blogPostsByBlogId: Array<NexusGenRootTypes['BlogPost'] | null> // [BlogPost]!
    blogPostsByUserId: Array<NexusGenRootTypes['BlogPost'] | null> // [BlogPost]!
    blogsByUserId: Array<NexusGenRootTypes['Blog'] | null> // [Blog]!
    userByEmail: NexusGenRootTypes['User'] | null // User
    userById: NexusGenRootTypes['User'] | null // User
    userByUsername: NexusGenRootTypes['User'] | null // User
  }
  Session: {
    // field return type
    expires: NexusGenScalars['DateTime'] | null // DateTime
    id: string // String!
    sessionToken: string // String!
    user: NexusGenRootTypes['User'] | null // User
    userId: string // String!
  }
  User: {
    // field return type
    accounts: Array<NexusGenRootTypes['Account'] | null> | null // [Account]
    bio: string | null // String
    blogComments: Array<NexusGenRootTypes['BlogComment'] | null> | null // [BlogComment]
    blogPosts: Array<NexusGenRootTypes['BlogPost'] | null> | null // [BlogPost]
    blogs: Array<NexusGenRootTypes['Blog'] | null> | null // [Blog]
    createdAt: NexusGenScalars['DateTime'] | null // DateTime
    email: string | null // String
    emailVerified: NexusGenScalars['DateTime'] | null // DateTime
    id: string // String!
    image: string | null // String
    name: string | null // String
    sessions: Array<NexusGenRootTypes['Session'] | null> | null // [Session]
    updatedAt: NexusGenScalars['DateTime'] | null // DateTime
    username: string | null // String
  }
  VerificationToken: {
    // field return type
    expires: string // String!
    identifier: string // String!
    token: string // String!
  }
}

export interface NexusGenFieldTypeNames {
  Account: {
    // field return type name
    access_token: 'String'
    expires_at: 'Int'
    id: 'String'
    id_token: 'String'
    provider: 'String'
    providerAccountId: 'String'
    refresh_token: 'String'
    scope: 'String'
    session_state: 'String'
    token_type: 'String'
    type: 'String'
    user: 'User'
    userId: 'String'
  }
  Blog: {
    // field return type name
    author: 'User'
    authorId: 'String'
    blogPosts: 'BlogPost'
    createdAt: 'DateTime'
    description: 'String'
    id: 'String'
    name: 'String'
    updatedAt: 'DateTime'
  }
  BlogComment: {
    // field return type name
    author: 'User'
    authorId: 'String'
    blogComments: 'BlogComment'
    blogPost: 'BlogPost'
    blogPostId: 'String'
    content: 'String'
    createdAt: 'DateTime'
    id: 'String'
    parent: 'BlogComment'
    parentId: 'String'
    updatedAt: 'DateTime'
  }
  BlogPost: {
    // field return type name
    author: 'User'
    authorId: 'String'
    blog: 'Blog'
    blogComments: 'BlogComment'
    blogId: 'String'
    content: 'String'
    createdAt: 'DateTime'
    id: 'String'
    published: 'Boolean'
    title: 'String'
    updatedAt: 'DateTime'
  }
  Mutation: {
    // field return type name
    UpdateBlogCommentInput: 'BlogComment'
    createBlog: 'Blog'
    createBlogComment: 'BlogComment'
    createBlogPost: 'Blog'
    updateBlog: 'Blog'
    updateBlogPost: 'Blog'
    updateUser: 'User'
  }
  Query: {
    // field return type name
    allBlogComments: 'BlogComment'
    allBlogPosts: 'BlogPost'
    allBlogs: 'Blog'
    allUsers: 'User'
    blogById: 'Blog'
    blogCommentById: 'BlogComment'
    blogCommentsByParentCommentId: 'BlogComment'
    blogCommentsByPostId: 'BlogComment'
    blogCommentsByUserId: 'BlogComment'
    blogPostById: 'BlogPost'
    blogPostsByBlogId: 'BlogPost'
    blogPostsByUserId: 'BlogPost'
    blogsByUserId: 'Blog'
    userByEmail: 'User'
    userById: 'User'
    userByUsername: 'User'
  }
  Session: {
    // field return type name
    expires: 'DateTime'
    id: 'String'
    sessionToken: 'String'
    user: 'User'
    userId: 'String'
  }
  User: {
    // field return type name
    accounts: 'Account'
    bio: 'String'
    blogComments: 'BlogComment'
    blogPosts: 'BlogPost'
    blogs: 'Blog'
    createdAt: 'DateTime'
    email: 'String'
    emailVerified: 'DateTime'
    id: 'String'
    image: 'String'
    name: 'String'
    sessions: 'Session'
    updatedAt: 'DateTime'
    username: 'String'
  }
  VerificationToken: {
    // field return type name
    expires: 'String'
    identifier: 'String'
    token: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    UpdateBlogCommentInput: {
      // args
      data: NexusGenInputs['UpdateBlogCommentInput'] // UpdateBlogCommentInput!
    }
    createBlog: {
      // args
      data: NexusGenInputs['CreateBlogInput'] // CreateBlogInput!
    }
    createBlogComment: {
      // args
      data: NexusGenInputs['CreateBlogCommentInput'] // CreateBlogCommentInput!
    }
    createBlogPost: {
      // args
      data: NexusGenInputs['CreateBlogPostInput'] // CreateBlogPostInput!
    }
    updateBlog: {
      // args
      data: NexusGenInputs['UpdateBlogInput'] // UpdateBlogInput!
    }
    updateBlogPost: {
      // args
      data: NexusGenInputs['UpdateBlogPostInput'] // UpdateBlogPostInput!
    }
    updateUser: {
      // args
      data: NexusGenInputs['UpdateUserInput'] // UpdateUserInput!
    }
  }
  Query: {
    blogById: {
      // args
      data: NexusGenInputs['BlogByIdInput'] // BlogByIdInput!
    }
    blogCommentById: {
      // args
      data: NexusGenInputs['BlogCommentByIdInput'] // BlogCommentByIdInput!
    }
    blogCommentsByParentCommentId: {
      // args
      data: NexusGenInputs['BlogCommentsByParentCommentIdInput'] // BlogCommentsByParentCommentIdInput!
    }
    blogCommentsByPostId: {
      // args
      data: NexusGenInputs['BlogCommentsByPostIdInput'] // BlogCommentsByPostIdInput!
    }
    blogCommentsByUserId: {
      // args
      data: NexusGenInputs['BlogCommentsByUserIdInput'] // BlogCommentsByUserIdInput!
    }
    blogPostById: {
      // args
      data: NexusGenInputs['BlogPostByIdInput'] // BlogPostByIdInput!
    }
    blogPostsByBlogId: {
      // args
      data: NexusGenInputs['BlogPostsByBlogIdInput'] // BlogPostsByBlogIdInput!
    }
    blogPostsByUserId: {
      // args
      data: NexusGenInputs['BlogPostsByUserIdInput'] // BlogPostsByUserIdInput!
    }
    blogsByUserId: {
      // args
      data: NexusGenInputs['BlogsByUserIdInput'] // BlogsByUserIdInput!
    }
    userByEmail: {
      // args
      data?: NexusGenInputs['UserByEmailInput'] | null // UserByEmailInput
    }
    userById: {
      // args
      data: NexusGenInputs['UserByIdInput'] // UserByIdInput!
    }
    userByUsername: {
      // args
      data?: NexusGenInputs['UserByUsernameInput'] | null // UserByUsernameInput
    }
  }
}

export interface NexusGenAbstractTypeMembers {}

export interface NexusGenTypeInterfaces {}

export type NexusGenObjectNames = keyof NexusGenObjects

export type NexusGenInputNames = keyof NexusGenInputs

export type NexusGenEnumNames = never

export type NexusGenInterfaceNames = never

export type NexusGenScalarNames = keyof NexusGenScalars

export type NexusGenUnionNames = never

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never

export type NexusGenAbstractsUsingStrategyResolveType = never

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context
  inputTypes: NexusGenInputs
  rootTypes: NexusGenRootTypes
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars
  argTypes: NexusGenArgTypes
  fieldTypes: NexusGenFieldTypes
  fieldTypeNames: NexusGenFieldTypeNames
  allTypes: NexusGenAllTypes
  typeInterfaces: NexusGenTypeInterfaces
  objectNames: NexusGenObjectNames
  inputNames: NexusGenInputNames
  enumNames: NexusGenEnumNames
  interfaceNames: NexusGenInterfaceNames
  scalarNames: NexusGenScalarNames
  unionNames: NexusGenUnionNames
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames']
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames']
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames']
  abstractTypeMembers: NexusGenAbstractTypeMembers
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType
  features: NexusGenFeaturesConfig
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {}
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {}
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {}
}
